### ISSUE TITLE
Rather than animating “date of investment vs cash multiplier after N years” plot over N, consider mkaing a 2D filled contour plot

### ISSUE THREAD

**Issue by fasiha** [zonination/investing#1]
Rather than (or in addition to!) an animation (or sequence of stills) per https://github.com/zonination/investing/blob/master/README.md#other-visualizations consider making a 2D [filled contour plot](http://www.mathworks.com/help/matlab/ref/contourf.html#examples) or image to show all three variables:

X axis: date sold.
Y axis: date bought.
Z axis (color): multiplier.

**Comment by zonination** [comment]
This is an interesting way to handle this kind of data. Here's a heatmap:

![Heatmap](https://raw.githubusercontent.com/zonination/investing/master/heatmap.png)
